version: '3'

services:
  buildozer:
    build: .
    volumes:
      - .:/app  # Only mount the current directory
      - ./bin:/app/bin  # Ensure the bin directory with APKs is accessible
    command: buildozer -v android debug